[package]
name = "get-certificate"
version = "0.2.0"
authors = ["fortanix.com"]
edition = "2018"
license = "MPL-2.0"
publish = false

[dependencies]
em-app = { path = "../../" }
mbedtls = { version = "0.12", default-features = false, features = ["std"] }
serde_json = "1.0"
